name: pageloader
version: 2.0.0-pre.1
author: Marc Fisher II <fisherii@google.com>
description: >
  Supports the creation of page objects that can be shared between in-browser tests
  and WebDriver tests.
homepage: https://github.com/google/pageloader
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  matcher: '^0.12.0'
  sync_webdriver: '^1.2.2+1'
  webdriver: '^0.10.0-pre.7'
dev_dependencies:
  path: '^1.3.5'
  test: '^0.12.0'
