name: pageloader
version: 2.0.0-pre.8
author: Marc Fisher II <fisherii@google.com>
description: >
  Supports the creation of page objects that can be shared between in-browser tests
  and WebDriver tests.
homepage: https://github.com/google/pageloader
environment:
  sdk: '>=1.11.0 <2.0.0'
dependencies:
  matcher: '^0.12.0+1'
  stack_trace: '^1.3.4'
  sync_webdriver: '^2.0.0-pre.0'
  unittest: '^0.11.6+1'
  webdriver: '^0.10.0-pre.13'
dev_dependencies:
  path: '^1.3.6'
  test: '^0.12.3+9'
